name: Check new version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # every month first day

jobs:
  check_version:
    uses: mpvkit/action/.github/workflows/check_version.yml@main
    secrets: inherit
    with:
      repository: 'haasn/libplacebo'
      library: 'libplacebo'
      pr_body: |
        https://github.com/haasn/libplacebo/blob/${{ env.LATEST_VERSION }}/RELEASING.md

        https://github.com/haasn/libplacebo/compare/${{ env.OLD_VERSION }}...${{ env.LATEST_VERSION }}
