name: Check new version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # every month first day

jobs:
  check_version:
    uses: mpvkit/BuildShared/.github/workflows/check_version.yml@main
    secrets: inherit
    with:
      repository: 'haasn/libplacebo'
      library: 'libplacebo'
      pr_body: |
        {REPOSITORY_URL}/releases/tag/{NEW_VERSION}

        {REPOSITORY_URL}/compare/{OLD_VERSION}...{NEW_VERSION}
